- name: Deploy Keycloak to AKS
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    namespace: keycloak
    target_namespace: keycloak
    manifest_dir: ../kubernetes

  tasks:
    - name: Set Azure subscription
      ansible.builtin.command:
        cmd: az account set  --subscription {{ subscription_id }}

    - name: Get AKS credentials
      ansible.builtin.command:
        cmd: az aks get-credentials --resource-group {{ resource_group }} --name {{ cluster_name }} --overwrite-existing

    - name: Create namespace
      ansible.builtin.shell:
        cmd: /usr/local/bin/kubectl create namespace {{ target_namespace }}
      ignore_errors: yes

    - name: Apply PostgreSQL deployment
      ansible.builtin.command:
        cmd: kubectl apply -f {{ manifest_dir }}/postgres-deployment.yaml -n {{ namespace }}

    - name: Apply PostgreSQL service
      ansible.builtin.command:
        cmd: kubectl apply -f {{ manifest_dir }}/postgres-service.yaml -n {{ namespace }}

    - name: Apply Keycloak deployment
      ansible.builtin.command:
        cmd: kubectl apply -f {{ manifest_dir }}/keycloak-deployment.yaml -n {{ namespace }}

    - name: Apply Keycloak service
      ansible.builtin.command:
        cmd: kubectl apply -f {{ manifest_dir }}/keycloak-service.yaml -n {{ namespace }}

    - name: Wait for Keycloak pod to be ready
      ansible.builtin.command:
        cmd: kubectl wait --for=condition=ready pod -l app=keycloak -n {{ namespace }} --timeout=120s
