apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --provider=keycloak
            - --client-id=static-client
            - --client-secret=GfxOQeV6Qs0FGJTufZC6iRgUdyRly9gY
            - --cookie-secret=edXdLSebVipplEGCOKheDxXLLWctnYNM
            - --cookie-domain=static.20.215.141.154.nip.io
            - --cookie-secure=false
            - --upstream=http://static-site-service.keycloak.svc.cluster.local:80
            - --redirect-url=http://static.20.215.141.154.nip.io/oauth2/callback
            - --oidc-issuer-url=http://keycloak.20.215.141.154.nip.io/realms/myrealm
            - --email-domain=*
            - --http-address=0.0.0.0:4180
            - --skip-provider-button=true
            - --scope="openid email profile"
            - --set-xauthrequest=true

          ports:
            - containerPort: 4180
